replicaCount: 2

image:
  repository: ravindra806/python-app-helm
  tag: prod        # dev image tag
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

resources: {}
serviceAccount:
  create: false
tests:
  enabled: false